// Mocks generated by Mockito 5.4.6 from annotations
// in incommonwith_flutter/test/repositories/catalog_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:incommonwith_flutter/data/models/cart_item.dart' as _i6;
import 'package:incommonwith_flutter/data/models/order.dart' as _i7;
import 'package:incommonwith_flutter/data/models/product.dart' as _i2;
import 'package:incommonwith_flutter/data/services/api_service.dart' as _i3;
import 'package:incommonwith_flutter/data/services/cache_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProduct_0 extends _i1.SmartFake implements _i2.Product {
  _FakeProduct_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Product>> fetchProducts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, []),
            returnValue: _i4.Future<List<_i2.Product>>.value(<_i2.Product>[]),
          )
          as _i4.Future<List<_i2.Product>>);

  @override
  _i4.Future<_i2.Product> fetchProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProduct, [id]),
            returnValue: _i4.Future<_i2.Product>.value(
              _FakeProduct_0(this, Invocation.method(#fetchProduct, [id])),
            ),
          )
          as _i4.Future<_i2.Product>);

  @override
  _i4.Future<List<String>> fetchCategories() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategories, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);
}

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i5.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> cacheProducts(List<_i2.Product>? products) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProducts, [products]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Product>> getCachedProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProducts, []),
            returnValue: _i4.Future<List<_i2.Product>>.value(<_i2.Product>[]),
          )
          as _i4.Future<List<_i2.Product>>);

  @override
  _i4.Future<void> cacheProductDetail(_i2.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProductDetail, [product]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Product?> getCachedProductDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductDetail, [id]),
            returnValue: _i4.Future<_i2.Product?>.value(),
          )
          as _i4.Future<_i2.Product?>);

  @override
  _i4.Future<void> cacheCart(List<_i6.CartItem>? items) =>
      (super.noSuchMethod(
            Invocation.method(#cacheCart, [items]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.CartItem>> getCachedCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedCart, []),
            returnValue: _i4.Future<List<_i6.CartItem>>.value(<_i6.CartItem>[]),
          )
          as _i4.Future<List<_i6.CartItem>>);

  @override
  _i4.Future<void> cacheOrder(_i7.Order? order) =>
      (super.noSuchMethod(
            Invocation.method(#cacheOrder, [order]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Order>> getCachedOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedOrders, []),
            returnValue: _i4.Future<List<_i7.Order>>.value(<_i7.Order>[]),
          )
          as _i4.Future<List<_i7.Order>>);

  @override
  _i4.Future<void> clearProductsCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearProductsCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
