// Mocks generated by Mockito 5.4.6 from annotations
// in incommonwith_flutter/test/viewmodels/checkout_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:incommonwith_flutter/data/models/cart_item.dart' as _i5;
import 'package:incommonwith_flutter/data/models/order.dart' as _i6;
import 'package:incommonwith_flutter/data/models/product.dart' as _i4;
import 'package:incommonwith_flutter/data/services/cache_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i2.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cacheProducts(List<_i4.Product>? products) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProducts, [products]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Product>> getCachedProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProducts, []),
            returnValue: _i3.Future<List<_i4.Product>>.value(<_i4.Product>[]),
          )
          as _i3.Future<List<_i4.Product>>);

  @override
  _i3.Future<void> cacheProductDetail(_i4.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProductDetail, [product]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Product?> getCachedProductDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductDetail, [id]),
            returnValue: _i3.Future<_i4.Product?>.value(),
          )
          as _i3.Future<_i4.Product?>);

  @override
  _i3.Future<void> cacheCart(List<_i5.CartItem>? items) =>
      (super.noSuchMethod(
            Invocation.method(#cacheCart, [items]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.CartItem>> getCachedCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedCart, []),
            returnValue: _i3.Future<List<_i5.CartItem>>.value(<_i5.CartItem>[]),
          )
          as _i3.Future<List<_i5.CartItem>>);

  @override
  _i3.Future<void> cacheOrder(_i6.Order? order) =>
      (super.noSuchMethod(
            Invocation.method(#cacheOrder, [order]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.Order>> getCachedOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedOrders, []),
            returnValue: _i3.Future<List<_i6.Order>>.value(<_i6.Order>[]),
          )
          as _i3.Future<List<_i6.Order>>);

  @override
  _i3.Future<void> clearProductsCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearProductsCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
