#!/bin/bash
FLUTTER_CMD="flutter"
if [ -d "flutter/bin" ]; then
  FLUTTER_CMD="flutter/bin/flutter"
fi

$FLUTTER_CMD build web --release \
  --dart-define=FIREBASE_WEB_API_KEY=$FIREBASE_WEB_API_KEY \
  --dart-define=FIREBASE_WEB_APP_ID=$FIREBASE_WEB_APP_ID \
  --dart-define=FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID \
  --dart-define=FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID \
  --dart-define=FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN \
  --dart-define=FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET \
  --dart-define=FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID
